### ISSUE TITLE
links to anchors to other headings not working

### ISSUE THREAD

**Issue by fabbra** [phseiff/github-flavored-markdown-to-html#22]
I have a markdown file with various headings and links inside the same file linking to those headings (i.e., linking to anchors in the same file) and converted this to HTML using the following code:
```
  gh-md-to-html ./test.md -w .
```

After conversion the "internal" links to other headings do not work anymore. My dirty workaround was to replace `id="user-content-` with `id="` and `class="anchor"` with an empty string.

```
  sed -i 's/id=\"user-content-/id=\"/g' test.html
  sed -i 's/class=\"anchor\" //g' test.html
```

I suppose there might be a more elegant solution to this?

**Comment by phseiff** [comment]
@fabbra Hello, and sorry for responding so late (several months, actually). I accidentally unwatched my own repository, and missed several issues in the process. I didn't realize this until right now, though.

My apologies for the delayed response; I will look into the issue (and hopefully fix it) this evening.

Did you find a workaround for yourself? I'm sorry if you had to stop using my tool due to me not fixing this in time.

> I suppose there might be a more elegant solution to this?

I think the behavior is probably either caused by GitHub's web API, or by some internal code of the module. In the later case, I just need to change some code, and in the former one, I will parse the HTML and do some changes to the parsed HTML (using `sed` would probably cause issues in case the string `"user-content-` is used within a code box, for example.

**Comment by phseiff** [comment]
Turns out the behavior to start header ids with `user-content-` is GitHub-specific behavior (and the offline-option that `gh-md-to-html` provides actually imitates that behavior on purpose). This behavior is also intended, because it ensures that the resulting HTML file can be embedded into any website, for example using a self-written static site generator, without clashing with anchors used by the rest of the website provided none of them starts with `user-content-`.

**Comment by phseiff** [comment]
I fixed this now by making the tool change all internal links from `<a href="#foobar">` to `<a href="#user-content-foobar">`.
Thanks again for filing this issue! :D

**Comment by fabbra** [comment]
perfect. thanks a lot for the fix!
