### ISSUE TITLE
table of contents `[[_TOC_]]` not available in HTML

### ISSUE THREAD

**Issue by fabbra** [phseiff/github-flavored-markdown-to-html#27]
When I have a table of contents (via the `[[_TOC_]]` keyword) in my markdown, the HTML will not show a table of contents but simply these few characters [[_TOC_]].
Is this a bug or simply a too "complicated" feature which will not be available?

**Comment by phseiff** [comment]
Hi,

Is the `[[_TOC_]]` feature available on GitHub/ part of the GitHub flavored markdown specification?
If not, then I'm afraid that this is out of scope (after all, the project aims to offer **GitHub-flavored** markdown conversion); if it is, on the other hand, then that's a bug and I will ofc do my best to fix it.

Did you use the `core_converter` option to use a different markdown parser than the one offered by GitHub? If yes, then that might be the reason.

I'm afraid I can't look any deeper into the issue at the moment, though, since I'll be occupied with private matters until the 9th of April; after that, I will further investigate into the issue.

**Comment by phseiff** [comment]
I just googled it quickly, and according to [this article](https://alexharv074.github.io/2018/08/28/auto-generating-markdown-tables-of-contents.html), the `[[_TOC_]]`-syntax is only supported by RedCarpet markdown; neither GitHub flavored nor pandoc-flavored markdown, so there isn't really a reason why this would need to be part of this markdown converter.

I could imagine adding an option to support all three syntaxes the article lists (`[[_TOC_]]`, `[toc]` and `{:toc}`) in the future, but I will have to think a little bit about this since I'm not sure if that's really a wide-spread enough feature to add it, considering every feature somewhat clutters the list of options.

**Comment by fabbra** [comment]
Hi, 
I am using this feature in GitLab and I must say that I was not fully aware that this is not a "general" feature. 
Thus, yes, fully understandable if this will not be included as a feature to avoid cluttering the list of options.
Sorry for not having checked this beforehand.
Thanks for your prompt replies!

**Comment by phseiff** [comment]
Don't worry, you're welcome!

**Comment by phseiff** [comment]
@fabbra You can update to `v1.9.0` now (`pip3 install --upgrade gh-md-to-html==1.9.0`), and use `--toc true` to enable the use of `[[_TOC__]]` (and the other syntaxes listed above) for adding a table of contents.
Note that the `[[_TOC__]]`-token must be stand-alone (the only thing within its line) for this to work, though.

**Comment by fabbra** [comment]
thanks a lot! 

it almost works...
i found an error of non-working links if the title contains a dash. 

in the following example file the link (via TOC) to the first three headings (not containing a dash) works whereas the links do not work to the last three headings (all containing a dash)
[test.md](https://github.com/phseiff/github-flavored-markdown-to-html/files/6334106/test.md)

**Comment by phseiff** [comment]
Thanks for testing and filing this issue!

I fixed this in `v1.10.2` now, and verified it works with this extended test file (both with GitHub's REST API as well as with the `-o OFFLINE` option):
[test-headings.md](https://github.com/phseiff/github-flavored-markdown-to-html/files/6335622/test-headings.md)

**Comment by fabbra** [comment]
seems to have fixed the bug. thanks!
